### ISSUE TITLE
SSE Proxy Guide

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla-docs#2]
Write a guided walkthrough describing how to configure `SSE Proxy` usecase, based on [`zilla-examples/sse.proxy.jwt`](https://github.com/aklivity/zilla-examples/tree/main/sse.proxy.jwt).

**Comment by vordimous** [comment]
The todo app will be the combined HTTP proxy guide once it is refactored in https://github.com/aklivity/zilla-docs/issues/48. Closing this ticket as it will be solved by https://github.com/aklivity/zilla-docs/issues/48.
