### ISSUE TITLE
bug: mark "Stdout Exporter" as an incubator feature

### ISSUE THREAD

**Issue by hedhyw** [aklivity/zilla-docs#208]
Configuration:
```yaml
telemetry:
  exporters:
    stdout:
      type: stdout
```

Zilla@0.9.74 prints:
```
At least one of the following sets of problems must be resolved.
zilla-1  | 1) [143,18][/telemetry/exporters/stdout/type] The value must be one of ["prometheus"].
zilla-1  | 2) [143,18][/telemetry/exporters/stdout/type] The string value must match the pattern "\$\{\{[\h\f\n\r\u000b?\u2028\u2029\ufeff]*([^[\h\f\n\r\u000b?\u2028\u2029\ufeff]\}]*)\.([^[\h\f\n\r\u000b?\u2028\u2029\ufeff]\}]*)[\h\f\n\r\u000b?\u2028\u2029\ufeff]*\}\}".
```

And it **works** if incubator features are **enabled**:
https://docs.aklivity.io/zilla/latest/how-tos/install.html#enable-incubator-features

It's probably better to indicate this on the following page:
https://docs.aklivity.io/zilla/latest/reference/config/telemetry/exporters/exporter-stdout.html

**Comment by vordimous** [comment]
Thank you for reporting this. The fix is on it's way.
