### ISSUE TITLE
Summary of problems discovered with `/zilla/latest`

### ISSUE THREAD

**Issue by jfallows** [aklivity/zilla-docs#31]
Reviewed https://aklivity-docs.pages.dev/zilla/latest to help prepare us for the `CNAME` cutover to `docs.aklivity.io`.

https://aklivity-docs.pages.dev/zilla/latest/
  Avian -> Aiven

https://aklivity-docs.pages.dev/zilla/latest/get-started/
  missing content

https://aklivity-docs.pages.dev/zilla/latest/get-started/install/
  missing content

https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/amazon-msk.html#create-a-client-certificate
  external link is broken

  seems like we want this instead to make it work pre- and post- cutover
  /msk-proxies/latest/reference/create-client-certificate-acm.html#issue-the-signed-certificate

https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/amazon-msk.html
  references zilla.json instead of zilla.yaml

https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/amazon-msk.html#export-client-and-ca-certificates
  First**,** you will export the Client Certificate 

https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/confluent-cloud.html#configure-zilla
  Let's configure zilla.json.

https://aklivity-docs.pages.dev/zilla/latest/guides/kafka-proxies/
  linked from Zilla home page, missing content

https://aklivity-docs.pages.dev/zilla/latest/reference/zpm/
  zpm clean links to zpm help
  need to rename clean.md -> help.md, clean-1.md -> clean.md, and fix links

https://aklivity-docs.pages.dev/zilla/latest/reference/zilla/clean.html
  bash:no-line-numbers showing in examples

https://aklivity-docs.pages.dev/zilla/latest/reference/zilla.yaml/guard-jwt.html#summary
  options.challenge is in the wrong position in the content, causing incorrect order in properties and toc

https://aklivity-docs.pages.dev/zilla/latest/reference/zilla.yaml/vault-filesystem.html
  example needs ${{env.KEYS_PASSWORD}}

**Comment by vordimous** [comment]
> https://aklivity-docs.pages.dev/zilla/latest/ Avian -> Aiven

fixed

> https://aklivity-docs.pages.dev/zilla/latest/get-started/ missing content
> https://aklivity-docs.pages.dev/zilla/latest/get-started/install/ missing content

I added the Getting Started content from the zilla repo as a placeholder. From the discussion on Monday, this is the area where the most work needs to be done.

> https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/amazon-msk.html#create-a-client-certificate external link is broken
> seems like we want this instead to make it work pre- and post- cutover /msk-proxies/latest/reference/create-client-certificate-acm.html#issue-the-signed-certificate

This is already handled in the proxy. Once the domain is updated, the existing external link will work.
https://docs.aklivity.io/aws/resources/create-client-certificate-acm#issue-the-signed-certificate
https://aklivity-docs.pages.dev/aws/resources/create-client-certificate-acm#issue-the-signed-certificate

> https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/amazon-msk.html references zilla.json instead of zilla.yaml
> https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/amazon-msk.html#export-client-and-ca-certificates First**,** you will export the Client Certificate
> https://aklivity-docs.pages.dev/zilla/latest/get-started/connecting-to-kafka/confluent-cloud.html#configure-zilla Let's configure zilla.json.
> https://aklivity-docs.pages.dev/zilla/latest/guides/kafka-proxies/ linked from Zilla home page, missing content

fixed

> https://aklivity-docs.pages.dev/zilla/latest/reference/zpm/ zpm clean links to zpm help need to rename clean.md -> help.md, clean-1.md -> clean.md, and fix links

fixed along with /zilla/clean.md -> help.md

> https://aklivity-docs.pages.dev/zilla/latest/reference/zilla/clean.html bash:no-line-numbers showing in examples

fixed

> https://aklivity-docs.pages.dev/zilla/latest/reference/zilla.yaml/vault-filesystem.html example needs ${{env.KEYS_PASSWORD}}

I've updated it along with the note about the zilla.properties. The `zilla.properties` file isn't mentioned anywhere else in the docs. Is that a legacy item or is it documented somewhere else?
